### ISSUE TITLE
No se ve el emoji de la bandera en W10/W11

### ISSUE THREAD

**Issue by emilianog94** [lucasromerodb/xboxito#1]
Buenas colega, congrats por la extensión, funciona de 10 en la galería de juegos! 

Lo único que noté fue que, a diferencia de la captura de pantalla, se me ve una abreviatura que dice AR en el lugar de la bandera. 

Dejo captura:
![image](https://user-images.githubusercontent.com/38828911/147618459-cf46195b-e21b-4a06-864d-19fef7808aa1.png)

Esto me pasa en:
Windows 10 21H2 (También lo probé con W11)
Chrome 96.0.4664.110

Según vi es porque [las banderas no tienen soporte para Windows](https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05?auth=1). Tal vez podés implementar una bandera de fallback SVG/PNG y mostrarla sólo cuando el userAgent es Windows.

**Comment by lucasromerodb** [comment]
Gracias Emiliano! Sale en el próximo release.
![image](https://user-images.githubusercontent.com/5304112/148660562-dee329b3-d969-406a-b9f3-6d0a49a76bd4.png)
